import {
  commandOutput,
  requestedOrLatestVersion,
  runUpdateScript,
  scriptPath,
  writeTextFile,
} from "coolheaded/core/updateScript.ts";
import type { CommandRunner } from "coolheaded/core/commandRunner.ts";
import { Effect } from "effect";
import type { JsonClient } from "coolheaded/core/httpClient.ts";
import { fetchJsonClient } from "coolheaded/core/fetchHttpClient.ts";
import { latestGitHubVersion } from "coolheaded/source/githubVersion.ts";

const NIXFMT_RELEASE_VERSION_PREFIX = "v";
const GENERATED_PACKAGE_FILE_PATH = scriptPath("generatedPackage.nix", import.meta.url);
const REPOSITORY_ROOT_PATH = scriptPath("../../", import.meta.url);
const GENERATED_PACKAGE_RELATIVE_PATH = "packages/nixfmt/generatedPackage.nix";

interface UpdateDependencies {
  readonly generatedPackageFilePath: string;
  readonly generatedPackageRelativePath: string;
  readonly jsonClient: JsonClient;
  readonly repositoryRootPath: string;
  readonly runner: CommandRunner;
}

function latestVersion(jsonClient: JsonClient): ReturnType<typeof latestGitHubVersion> {
  return latestGitHubVersion({ owner: "NixOS", repo: "nixfmt" }, jsonClient);
}

function sourceUrl(version: string): string {
  return `https://github.com/NixOS/nixfmt/archive/${NIXFMT_RELEASE_VERSION_PREFIX}${version}.tar.gz`;
}

function generatedPackageBody(
  version: string,
  dependencies: Readonly<UpdateDependencies>,
): Effect.Effect<string, Error> {
  return commandOutput(
    dependencies.runner,
    "nix",
    [
      "run",
      "--inputs-from",
      dependencies.repositoryRootPath,
      "nixpkgs#cabal2nix",
      "--",
      sourceUrl(version),
    ],
    dependencies.repositoryRootPath,
  );
}

function generatedPackageContents(
  version: string,
  dependencies: Readonly<UpdateDependencies>,
): Effect.Effect<string, Error> {
  return Effect.map(
    generatedPackageBody(version, dependencies),
    (body: string): string =>
      `# This file has been autogenerated with cabal2nix.\n# Update via packages/nixfmt/update.ts.\n${body}\n`,
  );
}

function formatGeneratedPackage(
  dependencies: Readonly<UpdateDependencies>,
): Effect.Effect<void, Error> {
  return Effect.asVoid(
    commandOutput(
      dependencies.runner,
      "nix",
      ["fmt", "--", dependencies.generatedPackageRelativePath],
      dependencies.repositoryRootPath,
    ),
  );
}

function updateProgram(
  args: readonly string[],
  dependencies: Readonly<UpdateDependencies>,
): Effect.Effect<void, Error> {
  return Effect.flatMap(
    requestedOrLatestVersion(
      args,
      (): ReturnType<typeof latestVersion> => latestVersion(dependencies.jsonClient),
    ),
    (version: string): Effect.Effect<void, Error> =>
      Effect.flatMap(
        generatedPackageContents(version, dependencies),
        (contents: string): Effect.Effect<void, Error> =>
          Effect.zipRight(
            writeTextFile(dependencies.generatedPackageFilePath, contents),
            formatGeneratedPackage(dependencies),
          ),
      ),
  );
}

async function main(
  args: readonly string[],
  dependencies: Readonly<UpdateDependencies>,
): Promise<void> {
  await Effect.runPromise(updateProgram(args, dependencies));
}

function cliProgram(args: readonly string[], runner: CommandRunner): Effect.Effect<void, Error> {
  return updateProgram(args, {
    generatedPackageFilePath: GENERATED_PACKAGE_FILE_PATH,
    generatedPackageRelativePath: GENERATED_PACKAGE_RELATIVE_PATH,
    jsonClient: fetchJsonClient,
    repositoryRootPath: REPOSITORY_ROOT_PATH,
    runner,
  });
}

runUpdateScript(import.meta.url, cliProgram);

export { main, updateProgram };
export type { UpdateDependencies };
