import {
  commandOutput,
  requestedOrLatestVersion,
  runUpdateScript,
  scriptPath,
  writeTextFile,
} from "coolheaded/core/updateScript.ts";
import { Effect } from "effect";
import { latestGitHubVersion } from "coolheaded/source/version.ts";

const NIXFMT_RELEASE_VERSION_PREFIX = "v";
const GENERATED_PACKAGE_FILE_PATH = scriptPath("generatedPackage.nix", import.meta.url);
const REPOSITORY_ROOT_PATH = scriptPath("../../", import.meta.url);
const GENERATED_PACKAGE_RELATIVE_PATH = "packages/nixfmt/generatedPackage.nix";
function latestVersion(): Effect.Effect<string, Error> {
  return latestGitHubVersion({
    owner: "NixOS",
    repo: "nixfmt",
  });
}

function sourceUrl(version: string): string {
  return `https://github.com/NixOS/nixfmt/archive/${NIXFMT_RELEASE_VERSION_PREFIX}${version}.tar.gz`;
}

function generatedPackageBody(version: string): Effect.Effect<string, Error> {
  return commandOutput(
    "nix",
    ["run", "--inputs-from", REPOSITORY_ROOT_PATH, "nixpkgs#cabal2nix", "--", sourceUrl(version)],
    REPOSITORY_ROOT_PATH,
  );
}

function generatedPackageContents(version: string): Effect.Effect<string, Error> {
  return Effect.map(
    generatedPackageBody(version),
    (body: string): string =>
      `# This file has been autogenerated with cabal2nix.\n# Update via packages/nixfmt/update.ts.\n${body}\n`,
  );
}

function formatGeneratedPackage(): Effect.Effect<void, Error> {
  return Effect.asVoid(
    commandOutput("nix", ["fmt", "--", GENERATED_PACKAGE_RELATIVE_PATH], REPOSITORY_ROOT_PATH),
  );
}

function updateProgram(args: readonly string[]): Effect.Effect<void, Error> {
  return Effect.flatMap(
    requestedOrLatestVersion(args, latestVersion),
    (version: string): Effect.Effect<void, Error> =>
      Effect.flatMap(
        generatedPackageContents(version),
        (contents: string): Effect.Effect<void, Error> =>
          Effect.zipRight(
            writeTextFile(GENERATED_PACKAGE_FILE_PATH, contents),
            formatGeneratedPackage(),
          ),
      ),
  );
}

async function main(args: readonly string[]): Promise<void> {
  await Effect.runPromise(updateProgram(args));
}

runUpdateScript(import.meta.url, updateProgram);

export { main };
