import {
  commandOutput,
  requestedOrLatestVersion,
  runUpdateScript,
  scriptPath,
  writeTextFile,
} from "coolheaded/core/updateScript.ts";
import type { CommandRunner } from "coolheaded/core/commandRunner.ts";
import { Effect } from "effect";
import type { JsonClient } from "coolheaded/core/httpClient.ts";
import { fetchJsonClient } from "coolheaded/core/fetchHttpClient.ts";
import { latestGitHubVersion } from "coolheaded/source/githubVersion.ts";

const NIXFMT_RELEASE_VERSION_PREFIX = "v";
const GENERATED_PACKAGE_FILE_PATH = scriptPath("generatedPackage.nix", import.meta.url);
const REPOSITORY_ROOT_PATH = scriptPath("../../", import.meta.url);
const GENERATED_PACKAGE_RELATIVE_PATH = "packages/nixfmt/generatedPackage.nix";
function latestVersion(jsonClient: JsonClient): ReturnType<typeof latestGitHubVersion> {
  return latestGitHubVersion({ owner: "NixOS", repo: "nixfmt" }, jsonClient);
}

function sourceUrl(version: string): string {
  return `https://github.com/NixOS/nixfmt/archive/${NIXFMT_RELEASE_VERSION_PREFIX}${version}.tar.gz`;
}

function generatedPackageBody(
  version: string,
  runner: CommandRunner,
): Effect.Effect<string, Error> {
  return commandOutput(
    runner,
    "nix",
    ["run", "--inputs-from", REPOSITORY_ROOT_PATH, "nixpkgs#cabal2nix", "--", sourceUrl(version)],
    REPOSITORY_ROOT_PATH,
  );
}

function generatedPackageContents(
  version: string,
  runner: CommandRunner,
): Effect.Effect<string, Error> {
  return Effect.map(
    generatedPackageBody(version, runner),
    (body: string): string =>
      `# This file has been autogenerated with cabal2nix.\n# Update via packages/nixfmt/update.ts.\n${body}\n`,
  );
}

function formatGeneratedPackage(runner: CommandRunner): Effect.Effect<void, Error> {
  return Effect.asVoid(
    commandOutput(
      runner,
      "nix",
      ["fmt", "--", GENERATED_PACKAGE_RELATIVE_PATH],
      REPOSITORY_ROOT_PATH,
    ),
  );
}

function updateProgram(
  args: readonly string[],
  runner: CommandRunner,
  jsonClient: JsonClient,
): Effect.Effect<void, Error> {
  return Effect.flatMap(
    requestedOrLatestVersion(
      args,
      (): ReturnType<typeof latestVersion> => latestVersion(jsonClient),
    ),
    (version: string): Effect.Effect<void, Error> =>
      Effect.flatMap(
        generatedPackageContents(version, runner),
        (contents: string): Effect.Effect<void, Error> =>
          Effect.zipRight(
            writeTextFile(GENERATED_PACKAGE_FILE_PATH, contents),
            formatGeneratedPackage(runner),
          ),
      ),
  );
}

async function main(
  args: readonly string[],
  runner: CommandRunner,
  jsonClient: JsonClient,
): Promise<void> {
  await Effect.runPromise(updateProgram(args, runner, jsonClient));
}

function cliProgram(args: readonly string[], runner: CommandRunner): Effect.Effect<void, Error> {
  return updateProgram(args, runner, fetchJsonClient);
}

runUpdateScript(import.meta.url, cliProgram);

export { main };
