import { assertEquals, assertInstanceOf, assertStrictEquals } from "@jsr/std__assert";
import { Effect } from "effect";
import { FakeCommandRunner } from "coolheadedTestSupport/commandRunner.ts";
import { UpdateError } from "coolheaded/core/updateScript.ts";
import { strictJsonClient } from "coolheadedTestSupport/httpClient.ts";
import { updateProgram } from "coolheadedPackageNixfmt";

const VERSION = "1.2.3";
const COMMAND_FAILURE = 23;
const COMMAND_OK = { code: 0, stderr: "", stdout: "" };
const CABAL_BODY = "{ lib }: lib";
const SENTINEL_BYTE = 255;
type Dependencies = Parameters<typeof updateProgram>[1];

function dependencies(
  generatedPackageFilePath: string,
  repositoryRootPath: string,
  runner: Readonly<FakeCommandRunner>,
): Dependencies {
  return {
    generatedPackageFilePath,
    generatedPackageRelativePath: "packages/nixfmt/generatedPackage.nix",
    jsonClient: strictJsonClient([]).client,
    repositoryRootPath,
    runner,
  };
}

Deno.test("nixfmt update runs cabal2nix then formats exact generated output", async (): Promise<void> => {
  const directory = await Deno.makeTempDir();
  const generatedPackageFilePath = `${directory}/generatedPackage.nix`;
  const runner = new FakeCommandRunner([
    {
      request: {
        command: [
          "nix",
          "run",
          "--inputs-from",
          directory,
          "nixpkgs#cabal2nix",
          "--",
          `https://github.com/NixOS/nixfmt/archive/v${VERSION}.tar.gz`,
        ],
        cwd: directory,
      },
      result: { ...COMMAND_OK, stdout: CABAL_BODY },
    },
    {
      request: {
        command: ["nix", "fmt", "--", "packages/nixfmt/generatedPackage.nix"],
        cwd: directory,
      },
      result: COMMAND_OK,
    },
  ]);
  try {
    await Effect.runPromise(
      updateProgram([VERSION], dependencies(generatedPackageFilePath, directory, runner)),
    );
    assertEquals(
      await Deno.readTextFile(generatedPackageFilePath),
      `# This file has been autogenerated with cabal2nix.\n# Update via packages/nixfmt/update.ts.\n${CABAL_BODY}\n`,
    );
    runner.assertExhausted();
  } finally {
    await Deno.remove(directory, { recursive: true });
  }
});

Deno.test("nixfmt update preserves generated bytes when cabal2nix fails", async (): Promise<void> => {
  const directory = await Deno.makeTempDir();
  const generatedPackageFilePath = `${directory}/generatedPackage.nix`;
  const sentinel = new Uint8Array([0, SENTINEL_BYTE, 1]);
  await Deno.writeFile(generatedPackageFilePath, sentinel);
  const failureResult = { code: COMMAND_FAILURE, stderr: "cabal2nix failed", stdout: "" };
  const runner = new FakeCommandRunner([
    {
      request: {
        command: [
          "nix",
          "run",
          "--inputs-from",
          directory,
          "nixpkgs#cabal2nix",
          "--",
          `https://github.com/NixOS/nixfmt/archive/v${VERSION}.tar.gz`,
        ],
        cwd: directory,
      },
      result: failureResult,
    },
  ]);
  try {
    const update = updateProgram(
      [VERSION],
      dependencies(generatedPackageFilePath, directory, runner),
    );
    const error = await Effect.runPromise(Effect.flip(update));
    assertInstanceOf(error, UpdateError);
    assertEquals(error.message, "Failed to run nix: exit 23: cabal2nix failed");
    assertEquals(await Deno.readFile(generatedPackageFilePath), sentinel);
    assertStrictEquals(runner.observations()[0]?.result, failureResult);
    runner.assertExhausted();
  } finally {
    await Deno.remove(directory, { recursive: true });
  }
});
