name: Update Dependencies
permissions:
  contents: read
concurrency:
  group: update-dependencies
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Space-separated package attrs"
        required: false
        default: ""
      inputs:
        description: "Space-separated flake inputs"
        required: false
        default: ""
      updatePackages:
        required: false
        type: boolean
        default: true
      updateFlakeInputs:
        required: false
        type: boolean
        default: true
      updateDenoDeps:
        required: false
        type: boolean
        default: true
      autoMerge:
        required: false
        type: boolean
        default: true
  schedule:
    - cron: "0 0,4,18,21 * * *"
jobs:
  packages:
    if: inputs.updatePackages != false
    uses: ./.github/workflows/updatePackages.yml
    with:
      autoMerge: ${{ inputs.autoMerge != false }}
      packages: ${{ inputs.packages }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  flakeInputs:
    if: inputs.updateFlakeInputs != false
    uses: ./.github/workflows/updateFlakeInputs.yml
    with:
      autoMerge: ${{ inputs.autoMerge != false }}
      inputs: ${{ inputs.inputs }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  denoDeps:
    if: inputs.updateDenoDeps != false
    uses: ./.github/workflows/updateDenoDeps.yml
    with:
      autoMerge: ${{ inputs.autoMerge != false }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
